[package]
name = "milkchess"
version = "0.0.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/benwilliamgraham/milkchess"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"

[profile.release]
opt-level = 3
lto = true
